### PR TITLE
deps: regenerating with new Protobuf (2.3.x)

### PR DESCRIPTION
**Pull request by mpeddada1**
To merge into 2.3.x branch. This PR was generated using Protobuf 3.19.6. Source-Link: https://github.com/googleapis/googleapis/commit/853e8a29cecd0816c8b003b299032c3a5168ef8b

### CODE REVIEW

**Comment by mpeddada1** [comment]
Compilation error:
```
 /home/runner/work/java-container/java-container/google-cloud-container/src/test/java/com/google/cloud/container/v1/it/ITSystemTest.java:[64,5] cannot find symbol
Error:    symbol:   variable Util
Error:    location: class com.google.cloud.container.v1.it.ITSystemTest
```

**Comment by mpeddada1** [comment]
Util.java is present in the [`2.3.x` branch ](https://github.com/googleapis/java-container/blob/f54dedf78b78997bef1479c851adab4cc64fcc22/google-cloud-container/src/test/java/com/google/cloud/container/v1/it/Util.java#L29) as well as the [ `main` branch](https://github.com/googleapis/java-container/blob/841936b448b9f66c3a97bf5c1fdcb858eaaa9638/google-cloud-container/src/test/java/com/google/cloud/container/v1/it/Util.java#L29)

**Comment by suztomo** [comment]
It seems the script doesn't take the hand-written library into account. Can you bring back the Util.java (`git checkout 2.3.x -- google-cloud-container/src/test/java/com/google/cloud/container/v1/it/Util.java` )?

**Comment by mpeddada1** [comment]
Thank you, yup bringing it back.

**Comment by mpeddada1** [comment]
Tests are passing now

**Review by suztomo — APPROVED** [review]

**Review by Shabirmean — APPROVED** [review]

**Comment by mpeddada1** [comment]
The `native image` job failures are expected for this PR since this branch is older than the one that contains the native image configurations/fixes.

**Pull request merged**
